language: java

jdk:
  - openjdk8
  - openjdk11

services: docker

script:
  - echo "Built!"

before_deploy:
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  - provider: script
    script: echo "OKKK"
    
  - provider: script
    skip_cleanup: true
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?(-SNAPSHOT)?$"
      jdk: openjdk8

  - provider: script
    skip_cleanup: true
    script: echo "Hello"
    on:
      jdk: openjdk8